# add sample compartment
melt[grepl('_50', variable), monsterdiepte := "25-50"]
melt[grepl('_25', variable), monsterdiepte := "0-25"]
melt[grepl('_OR', variable), `:=` (compartiment='OR')]
melt[grepl('Oeverzone', variable), `:=` (compartiment='OR')]
melt[grepl('_SB', variable), `:=` (monsterdiepte= "0-25", compartiment='SB')]
melt[variable %in% cols_slib, `:=` (monsterdiepte= "0-25", compartiment='SB')]
melt[grepl('_PW', variable), `:=` (monsterdiepte= "0-25", compartiment='PW')]
melt[grepl('_OW', variable), `:=` (monsterdiepte= "10-15", compartiment='OW')]
melt[variable %in% cols_wat, `:=` (monsterdiepte= "10-15", compartiment='OW')]
melt[grepl('Waterzone', variable), `:=` (compartiment='OW')]
# create names (maybe make mapping)
melt[,varnames:= gsub('umol','µmol',variable)] 
melt[,varnames:= gsub('uS_cm','(µS/cm)',variable)] 
melt[,varnames:= gsub("slib_redox_mgL", "slib redox (mV)",variable)] 
melt[,varnames:= gsub('mgL','(mg/l)',variable)] 
melt[,varnames:= gsub('_perc',' (%)',variable)] 
melt[,varnames:= gsub('_cm^','(cm)',variable)] 
melt[,varnames:= gsub('_m^','(m)',variable, fixed =TRUE)]
melt[,varnames:= gsub('_',' ',variable)] 
melt[,varnames:= gsub('water redox', 'water redox (mV)', variable)] 
melt[,varnames:= gsub("max slib", "maximale slibdikte (m)",variable)] 
melt[,varnames:= gsub("max wtd", "maximale waterdiepte (m)",variable)] 
melt[,varnames:= gsub("watbte", "waterbreedte (m)",variable)] 
melt[,varnames:= gsub("drglg", "gemeten drooglegging (m)",variable)] 
melt[,varnames:= gsub("drlg", "drooglegging obv peilen (m)",variable)] 
melt[variable == 'doorzicht2_mid_cm', value :=  value/100]
melt[,varnames:= gsub("doorzicht2 mid cm", "doorzicht (m)",variable)] 
melt[,varnames:= gsub("^insteek ", "indringingsweerstand insteek ",variable)] 
melt[,varnames:= gsub("^oever", "indringingsweerstand oever ",variable)] 
melt[,varnames:= gsub("^perceel ", "indringingsweerstand perceel ",variable)] 
melt[,varnames:= gsub("^holleoever", "onderholling oever (cm)",variable)] 
melt[,varnames:= gsub("SB", "in slib",variable)] 
melt[,varnames:= gsub("OW", "in oppervlaktewater",variable)] 
melt[,varnames:= gsub("PW", "in poriewater",variable)] 
melt[,varnames:= gsub("OR", "in de oever",variable)] 
unique(melt$varnames) 